test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,22 +1,12 @@
-name: dbt Cloud CI
+name: dbt Colibri Example
 on:
-  pull_request:
+  push:
     branches:
-      - main
-      - staging
+      - "*"
 jobs:
-  run_snowflake:
-    name: dbt Cloud PR CI Snowflake
+  deploy_colibri:
+    name: Deploy Colibri Example
     runs-on: macos-latest
-
-    env:
-      DBT_ACCOUNT_ID: 188483
-      DBT_PROJECT_ID: 283328
-      DBT_PR_JOB_ID: 552843
-      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
-      DBT_JOB_CAUSE: "GitHub Actions Request"
-      DBT_JOB_BRANCH: ${{ github.head_ref }}
-      DBT_JOB_SCHEMA_OVERRIDE: dbt_jsdx__pr_${{ github.head_ref}}
 
     steps:
       - uses: "actions/checkout@v4"
@@ -27,55 +17,31 @@ jobs:
         run: python3 -m pip install uv
       - name: Install deps
         run: uv pip install -r requirements.txt --system
-      - name: Run dbt Cloud job
-        run: python3 .github/workflows/scripts/dbt_cloud_run_job.py
+      - name: Initialize dbt
+        run: echo "dbt deps"
+      - name: Initialize dbt
+        run: echo "dbt compile && dbt test"
+      - name: Run Colibri
+        run: colibri generate
+      # Deploy to GitHub Pages (or other destination)
+      - name: Deploy Colibri HTML
+        run: |
+          # Ensure that the index.html is generated in the output dir
+          if [ -f dist/index.html ]; then
+            echo "Deploying HTML to GitHub Pages..."
+            
+            # If using GitHub Pages, copy the HTML file to the docs folder or desired directory
+            cp dist/index_inlined.html ./docs/index.html
 
-  run_bigquery:
-    name: dbt Cloud PR CI BigQuery
-    runs-on: macos-latest
-
-    env:
-      DBT_ACCOUNT_ID: 188483
-      DBT_PROJECT_ID: 275557
-      DBT_PR_JOB_ID: 561096
-      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
-      DBT_JOB_CAUSE: "GitHub Actions Request"
-      DBT_JOB_BRANCH: ${{ github.head_ref }}
-      DBT_JOB_SCHEMA_OVERRIDE: dbt_jsdx__pr_${{ github.head_ref}}
-
-    steps:
-      - uses: "actions/checkout@v4"
-      - uses: "actions/setup-python@v5"
-        with:
-          python-version: "3.12"
-      - name: Install uv
-        run: python3 -m pip install uv
-      - name: Install deps
-        run: uv pip install -r requirements.txt --system
-      - name: Run dbt Cloud job
-        run: python3 .github/workflows/scripts/dbt_cloud_run_job.py
-
-  run_postgres:
-    name: dbt Cloud PR CI Postgres
-    runs-on: macos-latest
-
-    env:
-      DBT_ACCOUNT_ID: 188483
-      DBT_PROJECT_ID: 288405
-      DBT_PR_JOB_ID: 577887
-      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
-      DBT_JOB_CAUSE: "GitHub Actions Request"
-      DBT_JOB_BRANCH: ${{ github.head_ref }}
-      DBT_JOB_SCHEMA_OVERRIDE: dbt_jsdx__pr_${{ github.head_ref}}
-
-    steps:
-      - uses: "actions/checkout@v4"
-      - uses: "actions/setup-python@v5"
-        with:
-          python-version: "3.12"
-      - name: Install uv
-        run: python3 -m pip install uv
-      - name: Install deps
-        run: uv pip install -r requirements.txt --system
-      - name: Run dbt Cloud job
-        run: python3 .github/workflows/scripts/dbt_cloud_run_job.py
+            # Configure Git for committing changes
+            git config --global user.name "GitHub Actions"
+            git config --global user.email "actions@github.com"
+            
+            # Commit the changes and push to the gh-pages branch
+            git add docs/index.html
+            git commit -m "Deploy Colibri HTML"
+            git push origin gh-pages
+          else
+            echo "Error: index.html not found in colibri_output!"
+            exit 1
+          fi
